services:
  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    container_name: valhalla
    ports:
      - "8002:8002"
    volumes: 
      - ./valhalla_data:/custom_files 
    environment:
      - tile_urls=https://download.geofabrik.de/europe/italy/nord-est-latest.osm.pbf
      - use_tiles_ignore_pbf=True
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - server_threads=2
    
  db:
    image: postgis/postgis:16-3.4
    container_name: pgis 
    environment: 
      POSTGRES_USER: gmaps
      POSTGRES_PASSWORD: dev 
      POSTGRES_DB: enhanced_gmaps 
    ports: 
    - "5432:5432"
    volumes: 
    - pgdata:/var/lib/postgresql/data 
  
volumes: 
  pgdata: